name: Deploy React App to AWS

on:
  push:
    branches:
      - pavan

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/react-app:latest

    - name: SSH to AWS instance and deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/react-app:latest
          docker stop react-app || true
          docker rm react-app || true
          docker run -d -p 80:5000 --name react-app ${{ secrets.DOCKER_USERNAME }}/react-app:latest